### ISSUE TITLE
Upgrade Godot-go library

### ISSUE THREAD

**Issue by ekozan** [godot-go/godot-go-demo-projects#8]
**Is your feature request related to a problem? Please describe.**
Upgrade to latest godot-go lib 

@pcting  i'll take this one but i'll wait for your PR on main lib  for closing ( https://github.com/godot-go/godot-go/issues/31 )

**Comment by pcting** [comment]
the demo apps has been reimplemented to work against the latest godot-go, which is built against godot 4.2-dev6+
